use_frameworks!

target 'Novagraph_Example' do
  pod 'Novagraph', :path => '../'

  target 'Novagraph_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
